"""GraphQL operations for SuperOps API"""

from .queries import *
from .mutations import *

__all__ = [
    # Queries
    'GET_TICKET_QUERY',
    'GET_TICKETS_BY_DATE_RANGE_QUERY', 
    'GET_ACTIVE_TICKETS_QUERY',
    'GET_TICKETS_BY_ASSIGNEE_QUERY',
    'GET_TICKET_ANALYTICS_QUERY',
    'SEARCH_TICKETS_QUERY',
    'GET_USER_QUERY',
    'GET_USERS_QUERY',
    'GET_TECHNICIANS_QUERY',
    
    # Mutations
    'CREATE_TICKET_MUTATION',
    'UPDATE_TICKET_MUTATION',
    'ASSIGN_TICKET_MUTATION',
    'RESOLVE_TICKET_MUTATION',
    'CLOSE_TICKET_MUTATION',
    'REOPEN_TICKET_MUTATION',
    'LOG_TIME_MUTATION',
    'UPDATE_TIME_ENTRY_MUTATION',
    'DELETE_TIME_ENTRY_MUTATION',
    'ADD_WORKLOG_MUTATION',
    'UPDATE_WORKLOG_MUTATION',
    'DELETE_WORKLOG_MUTATION',
    'ADD_COMMENT_MUTATION',
    'UPDATE_COMMENT_MUTATION',
    'DELETE_COMMENT_MUTATION',
    'CREATE_USER_MUTATION',
    'UPDATE_USER_MUTATION',
    'DEACTIVATE_USER_MUTATION',
]